project_id: 500514 #NEXT_CROWDIN_DOCUSAURUS_PROJECT_ID
api_token: 375bdea4ed65a3f0a7814799346c064ca47e66f61f6c7cda215cfe148cd7469481d521ca047787be #NEXT_CROWDIN_DOCUSAURUS_API_TOKEN
preserve_hierarchy: true
files: [
    # JSON
    {
      source: "/i18n/en/**/*",
      translation: "/i18n/%two_letters_code%/**/%original_file_name%",
    },
    # Docs
    {
      source: "/docs/**/*",
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%",
    },
    {
      source: "/versioned_docs/**/*",
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%",
    },
    # Blogs
    {
      source: "/blog/**/*",
      translation: "/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%",
    },
  ]
