project_id: NEXT_CROWDIN_DOCUSAURUS_PROJECT_ID
api_token: NEXT_CROWDIN_DOCUSAURUS_API_TOKEN
preserve_hierarchy: true
files: [
    # JSON
    {
      source: "/i18n/en/**/*",
      translation: "/i18n/%locale%/**/%original_file_name%",
    },
    # Docs
    {
      source: "/docs/**/*",
      translation: "/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%",
    },
    {
      source: "/versioned_docs/**/*",
      translation: "/i18n/%locale%/docusaurus-plugin-content-docs/**/%original_file_name%",
    },
    # Blogs
    {
      source: "/blog/**/*",
      translation: "/i18n/%locale%/docusaurus-plugin-content-blog/**/%original_file_name%",
    },
  ]
