apiVersion: v1
entries:
  pulsar:
  - apiVersion: v2
    appVersion: 2.7.4
    created: "2022-02-17T05:48:38.719970649Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 7add302ee84d71a1a11433266f4904f6740f04bec1fad7fe067ba61bc5727fc5
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.12/pulsar-2.7.12.tgz
    version: 2.7.12
generated: "2022-02-17T05:48:38.719985349Z"
