apiVersion: v1
entries:
  pulsar:
  - apiVersion: v1
    appVersion: 2.7.2
    created: "2021-11-12T15:56:55.960637651Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: aa0531316c37601c69f0f13b2fc749f9ce361722fce9b3ef75d0e329ca1e7c05
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.5/pulsar-2.7.5.tgz
    version: 2.7.5
  - apiVersion: v1
    appVersion: 2.7.2
    created: "2021-11-09T17:18:50.085604886Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 5f743a808c617103ea51466d19b101059c4a07ba33760f535aac5cf4f9c2a34b
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.4/pulsar-2.7.4.tgz
    version: 2.7.4
  - apiVersion: v1
    appVersion: 2.7.2
    created: "2021-09-10T00:56:39.780324095Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 52db0bb156d7bf7e89b0a2cd9db7bfa24cb0f33a7bcbe8270d694c0c02dcb476
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.3/pulsar-2.7.3.tgz
    version: 2.7.3
  - apiVersion: v1
    appVersion: 2.7.2
    created: "2021-06-03T08:32:20.657488129Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 4b9ef762aa5183bf80b500b5c9110e2fd1441d5512c97131ae78a698324daab4
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.2/pulsar-2.7.2.tgz
    version: 2.7.2
  - apiVersion: v1
    appVersion: 2.7.1
    created: "2021-03-16T07:46:24.80649093Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 873614a4efe68a3106ba1c1028fce25d9bbbb94daeaa56439a8792afffb0cf03
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.1/pulsar-2.7.1.tgz
    version: 2.7.1
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2020-12-04T04:15:12.44690667Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 7514c42971701c9b5889c65b83ea12e3d82f2727fcb88b77aaa2221dac86fb79
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0/pulsar-2.7.0.tgz
    version: 2.7.0
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2021-01-30T17:23:17.288984442Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 7af51e0b53569fa2fd6a461ff41dcc60df23283195c9e4b7e7dbbf686ff2cb2a
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0-1/pulsar-2.7.0-1.tgz
    version: 2.7.0-1
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2021-02-09T09:00:19.485753008Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: addaf76c03092b9ce8b427702a7131023713b177149cf220ba53e00dcd80d90a
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0-1/pulsar-2.7.0-1.tgz
    version: 2.7.0-1
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2021-01-30T17:27:44.643156571Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 94d7b360544ffe9a85c8d595cad1d56daeb9aa98873c98242c5e8ace99468c91
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0-1/pulsar-2.7.0-1.tgz
    version: 2.7.0-1
  - apiVersion: v1
    appVersion: 2.7.0
    created: "2021-01-08T05:27:15.548211942Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: bdbb841e75b5ed1fc9e65986def399690270c00c9282e0d616ddfa66faf2c558
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.7.0-1/pulsar-2.7.0-1.tgz
    version: 2.7.0-1
  - apiVersion: v1
    appVersion: 2.6.2
    created: "2020-12-04T03:32:37.181119982Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 00bbaf22df6ba20b5a63d7ee9a6bde518d715f659eee7cb6fe6afe4527460027
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.2-2/pulsar-2.6.2-2.tgz
    version: 2.6.2-2
  - apiVersion: v1
    appVersion: 2.6.2
    created: "2020-11-13T03:32:04.818944605Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 5c0193fde49ee6b277fc43a14f280b8010c8d0bfce5861ffb6f20e09f3067fbe
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.2-1/pulsar-2.6.2-1.tgz
    version: 2.6.2-1
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-09-08T02:06:54.135556929Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 3fe9f49a6c715ef36fad4c5d8ad2786e78f0cf693ac5db319171641b693248ed
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-10-15T10:42:47.984904328Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 4b67c2a1dae05e6f164a6ceff923b59927f84ea301cddeaf086a7728f1729eaf
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-09-22T14:48:12.627243579Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 2df7d813ce3a180766a3339d0057aaa51f791f3fe3729277dd0cfe94da351608
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-11-13T02:52:12.413925671Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 4aa2770403855380fadb8310653731bd459c98e9124064ac03029597a8305b34
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-11-11T18:49:06.171526352Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 64de61b6c6192c9247401a947bf0f8f79b819798cc5a8556ff0eb30ea61d70fc
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-09-21T18:16:54.544838106Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 4122ed592729aa33a0cd816223c648d9f36263f5a8f15037cad381d6bcbe7efe
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-2/pulsar-2.6.1-2.tgz
    version: 2.6.1-2
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-08-21T14:50:51.874906537Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: f0ee3c0165fe9388a11dcc4b325083a1546c8a0fc9080e8ed94e9f43563d1ce7
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-1/pulsar-2.6.1-1.tgz
    version: 2.6.1-1
  - apiVersion: v1
    appVersion: 2.6.1
    created: "2020-08-31T05:06:22.671294102Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 4a8343100a25942faef6e8db64169f19e3568be5d63e95b38c3f684843db2b3e
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.1-1/pulsar-2.6.1-1.tgz
    version: 2.6.1-1
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-07-02T06:19:53.443507716Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 2c6b316b1e465302b4ddd4331b3e05625d5b7f212186151b41006180088b8fa8
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.0/pulsar-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v1
    appVersion: 2.6.0
    created: "2020-08-13T17:20:37.21209387Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: bbcfcfdfe9088a006b5e497b1e255af7aed829c68b2e761857a48e9a9389dd4c
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.0-3/pulsar-2.6.0-3.tgz
    version: 2.6.0-3
  - apiVersion: v1
    appVersion: 2.6.0
    created: "2020-08-13T03:37:51.946509569Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: d86a542bdfee504099ac3388e494070b22417beb54315119f3a407d0197e1379
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.0-2/pulsar-2.6.0-2.tgz
    version: 2.6.0-2
  - apiVersion: v1
    appVersion: 2.6.0
    created: "2020-08-12T07:31:49.90685682Z"
    description: Apache Pulsar Helm chart for Kubernetes
    digest: 6705915742f55b4158e63d998d988dfe131d06a34ecaac4599101fedb3062b79
    home: https://pulsar.apache.org
    icon: http://pulsar.apache.org/img/pulsar.svg
    maintainers:
    - email: dev@pulsar.apache.org
      name: The Apache Pulsar Team
    name: pulsar
    sources:
    - https://github.com/apache/pulsar
    urls:
    - https://github.com/apache/pulsar-helm-chart/releases/download/pulsar-2.6.0-1/pulsar-2.6.0-1.tgz
    version: 2.6.0-1
generated: "2020-07-02T06:19:53.331144753Z"
